### ISSUE TITLE
VAR-SOM-6UL Support

### ISSUE THREAD

**Issue by atsawtelle** [varigit/meta-variscite-bsp-imx#10]
I'm currently using the VAR-SOM-6ULL with the i.MX6ULL processor for a project. I have run into an issue with trying to implement the Sony IMX577 CMOS image sensor, that it needs a driver from the v5.15 kernel

Is there any plan to support the VAR-SOM-6UL with Kirkstone (and the v5.15 kernel)? If not, would it be possible to put a newer driver in an older kernel version?

**Comment by varigigi** [comment]
Hi @Fozmy ,
for SW roadmaps, you may want to contact [Variscite sales](https://www.variscite.com/contact-us/).
For the time being, latest kernel is 5.4.142, available in [Yocto Dunfell](https://variwiki.com/index.php?title=VAR-SOM-6UL).
Feel free to backport whatever driver you need, but be aware that a 12.5 MP sensor (like IMX577) may provide low frame rates on DART-6UL (being based on entry level NXP iMX6UL).
Please let me know if you need further assistance.
Thanks
Best Regards
Pier

**Comment by darkdragon-001** [comment]
We also would like to update to `kirkstone` release for DART-6UL to make use of newer toolchain, kernel and other packages.

**Comment by moto-timo** [comment]
I have a [branch](https://github.com/moto-timo/meta-variscite-bsp/tree/kirkstone-imx6ul-var-dart) that builds the [`lf-5.10.y_var04` kernel](https://github.com/varigit/linux-imx/tree/lf-5.10.y_var04).

**Comment by moto-timo** [comment]
I only have `DART-6UL` hardware to test on, but @darkdragon-001 you should be able to test this. @Fozmy I would be interested to hear if this also works on `VAR-SOM-6UL`.

**Comment by darkdragon-001** [comment]
I am no longer working on this platform.

@thielepaul maybe you can point someone to test it? I think I left a branch and PR where I linked this issue ;)

**Comment by nsdrude** [comment]
@atsawtelle @moto-timo Variscite has released Yocto Kirkstone with Linux 5.15.71 for the DART-6UL and VAR-SOM-6UL: https://variwiki.com/index.php?title=DART-6UL
