### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by arnout** [varigit/meta-variscite-bsp-imx#20]
I would like to use the DART-6UL board I bought so I wanted to use this repository to build the firmware. Unfortunately, it seems this repository doesn't have a license, which means [I'm only allowed to view and fork it](https://choosealicense.com/no-permission/). I.e., I'm not allowed to use it to build the firmware.

I'm sure that hundreds of people have already illegally used this code, but my customer is not so lax about these things.

I'd suggest copying the LICENSE, LICENSE.GPL-2.0-only and LICENSE.MIT files from openembedded-core. MIT for the recipes and GPL-2.0 for the scripts seems very reasonable to me.

**Comment by nsdrude** [comment]
@arnout thank you for the suggestion.
