### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by Akbar-arm** [varigit/meta-variscite-bsp-imx#22]
There is no overall LICENSE file in this layer. Is it possible to list all the licenses that are used by recipes in this layer?

**Comment by nsdrude** [comment]
@Akbar-arm have you seen https://github.com/varigit/meta-variscite-bsp/commit/dc7dc8a6a0817e1a46a73e49c0e19c647d38e347 ?

**Comment by Akbar-arm** [comment]
Ah thank you, I was looking at the default branch.
