### ISSUE TITLE
Question about machines supported in mickledore-var01 branch

### ISSUE THREAD

**Issue by kraj** [varigit/meta-variscite-bsp-imx#34]
I have a basic question about machine support and branches. There are few branches in this repo. Its not clear which branch should be used for which machine. Is this documented somewhere ? I would like to use latest release i.e. `mickledore-var01` for var-som-mx8 based on `imx8qm-var-som` product. Is this supported combination ?

**Comment by eranmati** [comment]
Hi @kraj 
See: https://variwiki.com
More specifically, you can click on the VAR-SOM-MX8 picture and then on the "Release Notes" link of any specific release to see its relevant branches / manifest.

Regards,
Eran

**Comment by kraj** [comment]
@eranmati thanks I saw that in past. So it seems it will be multiple releases supporting multiple SOMs. Do you plan to support `master` branch as development branch where we can contribute fixes for any SOM? with yoe distro we support kirkstone and kirkstone-var02 branches with other layers being respective master branches which results in some fixes.
