### ISSUE TITLE
Build error on top of meta-freescale layer

### ISSUE THREAD

**Issue by Mothax** [varigit/meta-variscite-bsp-imx#37]
I get following error when building an image for imx8mp-var-dart on top of meta-freescale's [latest commit](https://git.yoctoproject.org/meta-freescale/commit/?h=kirkstone&id=47e0b467d8555e38a996b731977d9eed9ab02051) (branch kirkstone):

> ERROR: imx-boot-1.0-r0 do_compile: ExecutionError('/build/tmp/work/imx8mp-var-dart-poky-linux/imx-boot/1.0-r0/temp/run.do_compile.340', 1, None, None)
> ERROR: Logfile of failure stored in: /build/tmp/work/imx8mp-var-dart-poky-linux/imx-boot/1.0-r0/temp/log.do_compile.340
> Log data follows:
> | DEBUG: Executing shell function do_compile
> | Copying DTBs
> | NOTE: 8MQ/8MM/8MN/8MP boot binary build
> | NOTE: Copy ddr_firmware: lpddr4_pmu_train_1d_dmem_202006.bin from /build/tmp/deploy/images/imx8mp-var-dart -> /build/tmp/work/imx8mp-var-dart-poky-linux/imx-boot/1.0-r0/git/iMX8M
> | NOTE: Copy ddr_firmware: lpddr4_pmu_train_1d_imem_202006.bin from /build/tmp/deploy/images/imx8mp-var-dart -> /build/tmp/work/imx8mp-var-dart-poky-linux/imx-boot/1.0-r0/git/iMX8M
> | NOTE: Copy ddr_firmware: lpddr4_pmu_train_2d_dmem_202006.bin from /build/tmp/deploy/images/imx8mp-var-dart -> /build/tmp/work/imx8mp-var-dart-poky-linux/imx-boot/1.0-r0/git/iMX8M
> | NOTE: Copy ddr_firmware: lpddr4_pmu_train_2d_imem_202006.bin from /build/tmp/deploy/images/imx8mp-var-dart -> /build/tmp/work/imx8mp-var-dart-poky-linux/imx-boot/1.0-r0/git/iMX8M
> | cp: cannot stat '/build/tmp/deploy/images/imx8mp-var-dart/u-boot-spl.bin-imx8mp-var-dart-': No such file or directory
> | WARNING: exit code 1 from a shell command.
> ERROR: Task (/build/../work/sources/meta-freescale/recipes-bsp/imx-mkimage/imx-boot_1.0.bb:do_compile) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 3885 tasks of which 3884 didn't need to be rerun and 1 failed.
> 
> Summary: 1 task failed:
>   /build/../work/sources/meta-freescale/recipes-bsp/imx-mkimage/imx-boot_1.0.bb:do_compile
> Summary: There was 1 ERROR message, returning a non-zero exit code.

There is an imx-boot_1.0.bbappend file in meta-variscite-bsp-imx where [comple function for imx8m SOC_FAMILY](https://github.com/varigit/meta-variscite-bsp-imx/blob/hardknott/recipes-bsp/imx-mkimage/imx-boot_1.0.bbappend#L30) is called. 
Several variables has been removed from imx-boot_1.0.bb file in [meta-freescale layer in October](https://git.yoctoproject.org/meta-freescale/commit/?h=kirkstone&id=52a28a115d92c3d6a55f2cdfa4249ff499bcd2e3). Some of them still used in meta-variscite-bsp-imx.

Do you have any plans to add support to meta-variscite-bsp-imx to meet latest changes in meta-freescale layer for kirkstone branch?

**Comment by nsdrude** [comment]
@Mothax for the time being, we do not have any plans to update to the latest meta-freescale commit id for Kirkstone.

For additional support, please open a ticket in Variscite's customer support portal.

**Comment by floion** [comment]
Hi, any update here? We'd really like to use the latest Kirkstone as that allows to keep pace with latest security and functionality patches that yocto backports.
cc @eranmati ^

**Comment by nsdrude** [comment]
@floion thanks for following up. At the moment, we don't have any plans to update to the latest meta-freescale commit id for Kirkstone.

Please contact sales@variscite.com if you wish to discuss it further.

Thanks.

**Comment by stelitena** [comment]
Anyone needing to get this working quickly can use this fix to the imx_boot.bbappend file. This fix has been tested for the VAR-SOM-MX93 and VAR-SOM-MX8M. Works with latest meta-freescale layer for kirkstone as of time of writing.

```diff --git a/recipes-bsp/imx-mkimage/imx-boot_1.0.bbappend b/recipes-bsp/imx-mkimage/imx-boot_1.0.bbappend
index d496b9f..f3abcba 100644
--- a/recipes-bsp/imx-mkimage/imx-boot_1.0.bbappend
+++ b/recipes-bsp/imx-mkimage/imx-boot_1.0.bbappend
@@ -27,6 +27,18 @@ do_compile() {
     if ${deploy_optee}; then
         cp ${deploy_dir_image}/tee.bin ${boot_staging}
     fi
+
+    uboot_config_extra="${uboot_config}"
+    uboot_name_extra="u-boot-${machine}.bin-${uboot_config_extra}"
+    if [ -e ${deploy_dir_image}/${boot_tools}/${uboot_dtb_name}-${uboot_config_extra} ] ; then
+        uboot_dtb_name_extra="${uboot_dtb_name}-${uboot_config_extra}"
+    else
+        # backward compatibility
+        uboot_dtb_name_extra="${uboot_dtb_name}"
+    fi
+
+    boot_config_machine="imx-boot-${machine}-${uboot_config_extra}.bin"
+
     for target in ${imxboot_targets}; do
         compile_${soc_family}
         if [ "$target" = "flash_linux_m4_no_v2x" ]; then


```
